name: Publish Docker image
on:
  push:
    tags:
      - v*-mod*
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/jacaru/homepage-image
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
      - name: Extract upstream homepage version
        id: extract
        run: |
          tag="${{ steps.meta.outputs.version }}"
          version=${tag%-mod*}
          echo "::set-output name=version::$version"
      - name: Check out the upstream homepage repo
        uses: actions/checkout@v2
        with:
          repository: 'benphelps/homepage'
          ref: '${{steps.extract.outputs.version }}'
          path: 'homepage'
      - name: Apply downstream homepage patches
        run: |
          echo $(pwd)
          ls -1
          cd homepage
          git apply -v ../patch/*
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug
        run: |
          echo $(pwd)
          ls -l1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./homepath
          file: ./homepath/Dockerfile.basepath
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.extract.outputs.version }}
